### ISSUE TITLE
links to the manual on hydra are broken

### ISSUE THREAD

**Issue by FlorentBecker** [svanderburg/disnix#7]
on both nixos.org/disnix and in README.md, the link to the disnix manual is "https://hydra.nixos.org/job/disnix/disnix-trunk/tarball/latest/download-by-type/doc/manual". This page says "File /nix/store/a2ihxrk5k7yr9pxxp93d0z20646xnb4q-disnix-tarball-0.7/share/doc/disnix/manual does not exist.", which is a bit disappointing.

**Comment by jpotier** [comment]
Same problem here, for all the links to the manuals (either online or PDF)

**Comment by svanderburg** [comment]
Yes, that's because http://hydra.nixos.org uses a binary cache store and never stores anything locally anymore. It still provides the links to build artifacts despite that they are no longer available anymore.

I have to probably look for a different place/solution to store the manual for online access.

**Comment by jpotier** [comment]
Oh, I see. Thanks for the reply!

**Comment by svanderburg** [comment]
Should now be solved thanks to think Hydra change: https://github.com/NixOS/hydra/commit/7857f8325152daba97ef3764133ebc8b58e9860a
